#!/bin/bash
set -e

FWPATH="../"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

################## HW GISEN #######################

COPYDIR=GISEN
rm -f $COPYDIR/*

# GISEN
cd $FWPATH
touch conf_general.h
make -j8 build_args="-DHW_VERSION_GISEN"
cd $DIR
cp $FWPATH/build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_GISEN.bin

# Clean
cd $FWPATH
make clean
cd $DIR

